{
 "title": "Triton",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "nv_gpu_utilization" } }
  ]
 },
 "panels": [
  {
   "title": "Request success / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (model,version) (rate(nv_inference_request_success{job=\"$job\"}[30s]))",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Infer batch per exec ( Inf_count / Exec_count )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (model,version) (rate(nv_inference_count{job=\"$job\"}[30s])/rate(nv_inference_exec_count{job=\"$job\"}[30s]) )",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Queue time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (model,version) (nv_inference_queue_duration_us{job=\"$job\"}/nv_inference_request_success{job=\"$job\"} )",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Com infer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (model,version) (nv_inference_compute_infer_duration_us{job=\"$job\"}/nv_inference_request_success{job=\"$job\"} )",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "GPU Util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nv_gpu_utilization{job=\"$job\"}",
     "legendFormat": "Util"
    }
   ]
  },
  {
   "title": "Request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (model, version) (nv_inference_request_duration_us{job=\"$job\"}/nv_inference_request_success{job=\"$job\"} )",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Com input",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (model,version) (nv_inference_compute_input_duration_us{job=\"$job\"}/nv_inference_request_success{job=\"$job\"} )",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Com output",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (model,version) (nv_inference_compute_output_duration_us{job=\"$job\"}/nv_inference_request_success{job=\"$job\"})",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Power consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nv_gpu_power_usage{job=\"$job\"})",
     "legendFormat": "Total Power (W)"
    }
   ]
  },
  {
   "title": "Request fail / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (model) (rate(nv_inference_request_failure{job=\"$job\"}[5m]) )",
     "legendFormat": "{{model}}"
    }
   ]
  }
 ]
}